backend:
  name: github
  repo: abdalhameedbu50/law-firm
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "home"
    label: "الصفحة الرئيسية"
    files:
      - label: "محتوى الصفحة الرئيسية"
        name: "homepage"
        file: "content/home.json"
        fields:
          - { label: "عنوان الهيرو", name: "hero_title", widget: "string", required: false }
          - { label: "وصف الهيرو", name: "hero_subtitle", widget: "text", required: false }

          - { label: "نص الزر الأساسي", name: "hero_cta_text", widget: "string", required: false }
          - { label: "رابط الزر الأساسي", name: "hero_cta_url", widget: "string", required: false }
          - { label: "نص الزر الثانوي", name: "hero_cta2_text", widget: "string", required: false }
          - { label: "رابط الزر الثانوي", name: "hero_cta2_url", widget: "string", required: false }

          - { label: "الهاتف", name: "contact_phone", widget: "string", required: false }
          - { label: "رقم واتساب (بدون +)", name: "contact_whatsapp", widget: "string", required: false }
          - { label: "البريد الإلكتروني", name: "contact_email", widget: "string", required: false }
          - { label: "العنوان", name: "contact_address", widget: "string", required: false }

          - { label: "سطر الشعار في الفوتر", name: "footer_tagline", widget: "string", required: false }
          - { label: "شعار الموقع (اللوجو)", name: "site_logo", widget: "image", required: false }
          - { label: "رابط واتساب كامل", name: "whatsapp_link", widget: "string", hint: "مثال: https://wa.me/966503169240", required: false }

          - label: "شعارات العملاء"
            name: "clients"
            widget: list
            required: false
            fields:
              - { label: "صورة الشعار", name: "image", widget: "image", required: false }
              - { label: "النص البديل (alt)", name: "alt", widget: "string", required: false }
