backend:
  name: github
  repo: abdalhameedbu50/law-firm
  branch: main

media_folder: "static/uploads"     # where images are saved in the repo
public_folder: "/uploads"          # how images are referenced by the site

# Optional: enable draft → review → publish workflow
publish_mode: editorial_workflow

collections:
  # Home page content (stored as a JSON file)
  - name: "home"
    label: "الصفحة الرئيسية"
    files:
      - label: "محتوى الصفحة الرئيسية"
        name: "homepage"
        file: "content/home.json"
        fields:
          - { label: "عنوان الهيرو", name: "hero_title", widget: "string" }
          - { label: "وصف الهيرو", name: "hero_subtitle", widget: "text" }

          - { label: "نص الزر الأساسي", name: "hero_cta_text", widget: "string" }
          - { label: "رابط الزر الأساسي", name: "hero_cta_url", widget: "string" }
          - { label: "نص الزر الثانوي", name: "hero_cta2_text", widget: "string" }
          - { label: "رابط الزر الثانوي", name: "hero_cta2_url", widget: "string" }

          - { label: "الهاتف", name: "contact_phone", widget: "string" }
          - { label: "رقم واتساب (بدون +)", name: "contact_whatsapp", widget: "string" }
          - { label: "البريد الإلكتروني", name: "contact_email", widget: "string" }
          - { label: "العنوان", name: "contact_address", widget: "string" }

          - { label: "سطر الشعار في الفوتر", name: "footer_tagline", widget: "string" }