backend:
  name: github
  repo: your-github-username/your-repo-name   # 🔑 change this
  branch: main

media_folder: "static/uploads"      # where images are stored in repo
public_folder: "/uploads"           # path used in your site

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
